# Generated by Django 2.1.5 on 2019-03-03 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0002_auto_20190303_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('white_user_id', models.IntegerField()),
                ('black_user_id', models.IntegerField()),
                ('move_number', models.IntegerField()),
                ('move_algebraic', models.CharField(max_length=32)),
                ('turn', models.CharField(max_length=8)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Games')),
            ],
        ),
    ]
