# Generated by Django 2.1.5 on 2019-03-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id_1', models.IntegerField()),
                ('user_id_2', models.IntegerField()),
                ('white_user_id', models.IntegerField()),
                ('black_user_id', models.IntegerField()),
                ('difficulty_level', models.IntegerField(default=None)),
            ],
        ),
    ]
