# Generated by Django 2.2 on 2019-06-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190303_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='difficulty_level',
            new_name='difficulty',
        ),
        migrations.AddField(
            model_name='games',
            name='ongoing',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
